module.exports = {
  ArticleTokenType: {
    BLOCK_QUOTE: 0,
    BOLD_ITALIC: 1,
    BOLD: 2,
    ITALIC: 3,
    HEADER: 4,
    REF: 5,
    LINK: 6,
    LIST: 7,
    TABLE_OF_CONTENTS: 8,
    PARAGRAPH_BREAK: 9,
    EMPHASIS: 10,
    ELEM: 11,
    CODE_BLOCK: 12,
    REFERENCE: 13,
    PARAGRAPH: 14,
    OBJ_LINK: 15,
  },
};
